version: "3.9"
services:
  go:
    links:
      - db
    build:
      context: ./go
      dockerfile: Dockerfile
    # environment:
    #   SECRET: ciao
    ports:
      - "8080:8080"
    networks:
      - "benchmarks"
  admin:
    links:
      - db
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    networks:
      - "benchmarks"
  nginx:
    build: ./nginx
    ports:
    - "9000:80"
    depends_on:
    - admin
    - go
  db:
    image: mariadb:10.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: didPlus
      MYSQL_USER: MoraGames
      MYSQL_PASSWORD: MoraGames
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - "3306"
    volumes:
      - ./db-dump:/var/lib/mysql
    networks:
      - "benchmarks"

volumes:
  mariadb:

networks:
  benchmarks: